import 'package:my_portflio/models/project_model.dart';

final projects = [
  ProjectModel(
    id: 1,
    title: 'متجر إلكتروني',
    description:
        'تطبيق متجر إلكتروني بتصميم عصري وسهل الاستخدام، يتيح للمستخدمين تصفح المنتجات حسب الأقسام، مشاهدة التفاصيل مع الصور والأسعار، إضافة المنتجات إلى السلة، وإتمام عملية الشراء بسهولة. يتميز بواجهة بسيطة وسريعة تدعم البحث، العروض الخاصة، وتتبع الطلبات.',
    technologies: ['فلاتر', 'فايربيس', 'سترايب'],
    imageUrl: '/images/projects/ecomm/ecomm.png',
    githubUrl: 'https://github.com',
    liveUrl: '',
    gallary: [
      '/images/projects/ecomm/images/Shot.png',
      '/images/projects/ecomm/images/Shot(1).png',
      '/images/projects/ecomm/images/Shot(2).png',
      '/images/projects/ecomm/images/Shot(3).png',
      '/images/projects/ecomm/images/Shot(4).png',
      '/images/projects/ecomm/images/Shot(5).png',
      '/images/projects/ecomm/images/Shot(6).png',
      '/images/projects/ecomm/images/Shot(7).png',
      '/images/projects/ecomm/images/Shot(8).png',
    ],
  ),
  ProjectModel(
    id: 2,
    title: 'حجز تذاكر',
    description:
        'تطبيق لحجز التذاكر يوفر واجهة سهلة وسريعة، يتيح للمستخدمين تصفح الفعاليات والمواعيد، اختيار المقاعد، وإتمام عملية الحجز والدفع بكل سهولة، مع إمكانية تتبع الحجوزات واستلام التذاكر إلكترونيًا.',
    technologies: ['فلاتر', 'فايربيس', 'سترايب'],
    imageUrl: '/images/projects/booking/booking.png',
    githubUrl: 'https://github.com',
    liveUrl: '',
    gallary: [
      '/images/projects/booking/images/Shot.png',
      '/images/projects/booking/images/Shot(1).png',
      '/images/projects/booking/images/Shot(2).png',
      '/images/projects/booking/images/Shot(3).png',
      '/images/projects/booking/images/Shot(4).png',
      '/images/projects/booking/images/Shot(5).png',
    ],
  ),
  ProjectModel(
    id: 3,
    title: "دفتر يوميات",
    description:
        'تطبيق محاسبي لإدارة المعاملات المالية اليومية، يتيح تسجيل القيود المحاسبية مثل المصروفات والإيرادات، متابعة الحسابات، وإصدار التقارير المالية بدقة، مع واجهة بسيطة وسهلة الاستخدام لتنظيم الأعمال المحاسبية بكفاءة.',
    technologies: ['فلاتر', 'فايربيس', 'سترايب'],
    imageUrl: '/images/projects/dialy/dialy.png',
    githubUrl: 'https://github.com',
    liveUrl: '',
    gallary: [
      '/images/projects/dialy/images/Shot.png',
      '/images/projects/dialy/images/Shot(1).png',
      '/images/projects/dialy/images/Shot(2).png',
      '/images/projects/dialy/images/Shot(3).png',
      '/images/projects/dialy/images/Shot(4).png',
      '/images/projects/dialy/images/Shot(5).png',
      '/images/projects/dialy/images/Shot(6).png',
      '/images/projects/dialy/images/Shot(7).png',
    ],
  ),
  ProjectModel(
    id: 4,
    title: "صفحة شخصية",
    description:
        'تطبيق بواجهة مخصصة للصفحة الشخصية، يتيح للمستخدم عرض وتحديث بياناته مثل الاسم، الصورة، ومعلومات الاتصال، مع إمكانية إدارة الإعدادات ومتابعة النشاطات الخاصة به بسهولة وواجهة بسيطة.',

    technologies: ['فلاتر', 'فايربيس', 'سترايب'],
    imageUrl: '/images/projects/profile/profile.png',
    githubUrl: 'https://github.com',
    liveUrl: '',
    gallary: [
      '/images/projects/profile/images/Shot.png',
      '/images/projects/profile/images/Shot(1).png',
      '/images/projects/profile/images/Shot(2).png',
      '/images/projects/profile/images/Shot(3).png',
      '/images/projects/profile/images/Shot(4).png',
      '/images/projects/profile/images/Shot(5).png',
    ],
  ),
  ProjectModel(
    id: 5,
    title: "تطبيق استوديو",
    description:
        'تطبيق استوديو للاستماع إلى الأغاني وتحميلها بسهولة، يتيح للمستخدم البحث عن الأغاني بالاسم، تشغيلها بجودة عالية، وتحميلها للاستماع دون اتصال، مع إمكانية طلب أغنية مخصصة حسب رغبة المستخدم.',
    technologies: ['فلاتر', 'فايربيس', 'سترايب'],
    imageUrl: '/images/projects/newart/newart.png',
    githubUrl: 'https://github.com',
    liveUrl: '',
    gallary: [
      '/images/projects/newart/images/Shot.png',
      '/images/projects/newart/images/Shot(1).png',
      '/images/projects/newart/images/Shot(2).png',
      '/images/projects/newart/images/Shot(3).png',
      '/images/projects/newart/images/Shot(4).png',
      '/images/projects/newart/images/Shot(5).png',
      '/images/projects/newart/images/Shot(6).png',
      '/images/projects/newart/images/Shot(7).png',
    ],
  ),
  ProjectModel(
    id: 6,
    title: "عقود وسندات",
    description:
        'تطبيق لإدارة العقود والسندات، يتيح إنشاء وتعديل وتخزين العقود والسندات بشكل آمن ومنظم، مع إمكانية البحث السريع وتتبع حالة العقود، وتوفير تنبيهات للمواعيد الهامة، مما يسهل إدارة المستندات القانونية بكفاءة.',
    technologies: ['فلاتر', 'فايربيس', 'سترايب'],
    imageUrl: '/images/projects/acd/acd.png',
    githubUrl: 'https://github.com',
    liveUrl: '',
    gallary: [
      '/images/projects/acd/images/Shot.png',
      '/images/projects/acd/images/Shot(1).png',
      '/images/projects/acd/images/Shot(2).png',
      '/images/projects/acd/images/Shot(3).png',
      '/images/projects/acd/images/Shot(4).png',
      '/images/projects/acd/images/Shot(5).png',
      '/images/projects/acd/images/Shot(6).png',
      '/images/projects/acd/images/Shot(7).png',
    ],
  ),
  ProjectModel(
    id: 7,
    title: "نضام محاسبي",
    description:
        'نظام محاسبي متكامل لإدارة الحسابات المالية للشركات والمؤسسات، يتيح تسجيل القيود المحاسبية، تتبع المصروفات والإيرادات، إدارة الأصول والخصوم، وإصدار التقارير المالية الدقيقة مثل الميزانية وقائمة الدخل، مع واجهة سهلة الاستخدام تدعم التحليلات المالية واتخاذ القرارات.',
    technologies: ['فلاتر', 'فايربيس', 'سترايب'],
    imageUrl: '/images/projects/accounts/accounts.png',
    githubUrl: 'https://github.com',
    liveUrl: '',
    gallary: [
      '/images/projects/accounts/images/Shot.png',
      '/images/projects/accounts/images/Shot(1).png',
      '/images/projects/accounts/images/Shot(2).png',
      '/images/projects/accounts/images/Shot(3).png',
      '/images/projects/accounts/images/Shot(4).png',
      '/images/projects/accounts/images/Shot(5).png',
      '/images/projects/accounts/images/Shot(6).png',
      '/images/projects/accounts/images/Shot(7).png',
    ],
  ),
];

final skills = [
  'Flutter',
  'Dart',
  'State Management',

  'REST APIs',
  'Firebase',
  'Custom Animations',
  'UI/UX Design',
  'Testing',
  'Agile Development',
  'Git',
];
